### ISSUE TITLE
--default-expires is not very user-friendly

### ISSUE THREAD

**Issue by Akuli** [adder46/dpaster#3]
If I want to config `--default-expires`, I do `dpaster config --help`, which says:

```
  --default-expires OPT           Choose default expiry time (e.g. onetime,
                                  never, 3600, 604800, 2592000)
```

It doesn't make sense to say "the paste expires in 2592000", so I'm confused because I don't know what those numbers mean. It would, however, make sense to say that "the paste expires in 2592000 seconds", or (much more user-friendly), "the paste expires in 30 days".

I see a couple alternatives for fixing this:

1. (easier to implement, but not very nice to users) Mention that the expiry is given as seconds in `--default-expires` help.
2. (more work to implement, but much more user-friendly) Add some nicer syntax for `--default-expires` instead of raw numbers that represent seconds. For example, `--default-expires=15min`, `--default-expires=2h`, `--default-expires=30d`.

**Comment by adder46** [comment]
Fixed.

Try `dpaster config --default-expires day`, for instance.
